# Generated by Django 3.1.1 on 2020-10-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201005_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
